name: "GitHub Release Downloader"
description: "GitHub action creates a deployment into an existing Amplify aplication"
branding:
  color: yellow
  icon: at-sign
inputs:
  tag:
    description: Release Tag
    required: true
  access_token:
    description: "Your GitHub Access Token, defaults to: {{ github.token }}"
    default: "${{ github.token }}"
    required: true

runs:
  using: "node12"
  main: "./dist/index.js"
